# Generated by Django 5.2.1 on 2025-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0002_remove_transaction_note_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
