# Generated by Django 5.2.1 on 2025-05-13 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0004_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('gali', 'Gali'), ('faridabad', 'Faridabad'), ('disawer', 'Disawer'), ('ghaziabad', 'Ghaziabad'), ('gurgaon', 'Gurgaon')], max_length=20)),
                ('bet_type', models.CharField(choices=[('number', 'Number'), ('andar', 'Andar'), ('bahar', 'Bahar')], max_length=10)),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_win', models.BooleanField(default=False)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stapp.bet')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_bets', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
