# Generated by Django 5.2.1 on 2025-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0005_bet_referralcommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='depositrequest',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.CharField(choices=[('gali', 'Gali'), ('faridabad', 'Faridabad'), ('disawer', 'Disawer'), ('ghaziabad', 'Ghaziabad'), ('jaipur king', 'Jaipur King'), ('diamond king', 'Diamond King')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='utr_number',
            field=models.CharField(max_length=50),
        ),
    ]
