# Generated by Django 5.2.1 on 2025-05-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0006_remove_depositrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
