# Generated by Django 5.2.1 on 2025-05-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0007_remove_withdrawrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
