# Generated by Django 5.2.1 on 2025-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0008_withdrawrequest_approved_at_withdrawrequest_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='wallet',
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
