# Generated by Django 5.2.1 on 2025-05-27 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0009_remove_withdrawrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommission',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
