# Generated by Django 5.2.1 on 2025-05-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0012_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
