# Generated by Django 5.2.1 on 2025-05-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0013_remove_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stapp.depositrequest'),
        ),
    ]
