# Generated by Django 5.2.1 on 2025-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0014_transaction_related_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='game',
            new_name='game_name',
        ),
    ]
