# Generated by Django 5.2.1 on 2025-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0015_rename_game_bet_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10),
        ),
    ]
