# Generated by Django 5.2.1 on 2025-06-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0016_bet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcommission',
            name='commission_type',
            field=models.CharField(choices=[('signup_bonus', 'Signup Bonus'), ('bet_commission', 'Bet Commission')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referralcommission',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stapp.bet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
