# Generated by Django 5.2.1 on 2025-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0017_referralcommission_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
