# Generated by Django 5.2.1 on 2025-06-10 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0020_userdatabackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_winnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_winnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
