# Generated by Django 5.2.1 on 2025-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0023_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaredResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('winning_number', models.CharField(max_length=3)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
